# Generated by Django 4.2.4 on 2023-09-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealrate',
            options={'verbose_name': 'Meal Rate', 'verbose_name_plural': 'Meal Rates'},
        ),
        migrations.AlterModelTable(
            name='mealrate',
            table='meal_rate',
        ),
    ]
